### PR TITLE
WIP : make more fields dynamic in cf-mysql-template.yml 

### PR DESCRIPTION
**Pull request by axelfauvel**
This an internal orange review, once merged, on orange-cloudfoundry branch, we'll send a new PR to the upstream repo. Following is the planned PR text to be submitted to the community:

@gberche-orange @poblin-orange : Do you need to add dynamic field before submitting this PR to community ?

----

adding dynamic fields in cf-mysql-template

### CODE REVIEW

**Comment by poblin-orange** [comment]
as of cf-mysql v32, the mariadb log level should be configurable (properties in bosh release, but not overridable in manifest generation scripts). 


```
diff --git a/manifest-generation/cf-mysql-template.yml b/manifest-generation/cf-mysql-template.yml
index 40c6752..f6ea56e 100644
--- a/manifest-generation/cf-mysql-template.yml
+++ b/manifest-generation/cf-mysql-template.yml
@@ -80,6 +80,8 @@ properties:
       persistent_disk: (( disk_pools.mysql-persistent-disk.disk_size ))
       server_audit_events: (( property_overrides.mysql.server_audit_events || nil ))
       server_audit_excluded_users: (( property_overrides.mysql.server_audit_excluded_users || nil ))
+      userstat: (( property_overrides.mysql.userstat || false ))
+      wsrep_debug: (( property_overrides.mysql.wsrep_debug || 0 ))
       cluster_health:
         password: (( property_overrides.mysql.cluster_health.password ))
     proxy:

```

**Comment by axelfauvel** [comment]
@gberche-orange : Will implement your title & description. Concerning v-boutes commit, I will look on community repo if it has been implemented yet.

**Comment by axelfauvel** [comment]
PR here : https://github.com/cloudfoundry/cf-mysql-release/pull/144

**Comment by gberche-orange** [comment]
upstream merged, closing

**Pull request closed without merging**
